--- 
title: "The WIPO Manual on Open Source Patent Analytics"
date: "2016"
output: bookdown::gitbook
site: bookdown::bookdown_site
documentclass: book
github-repo: wipo-analytics/manual_bookdown
description: "A practical introduction to free and open source tools for patent analytics."

---
```{r echo=FALSE, eval=FALSE}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62774602-2', 'auto');
  ga('send', 'pageview');

</script>
```

#Frontmatter {-}

##Authorship

The Manual was written by Dr. Paul Oldham from [One World Analytics](http://oneworldanalytics.com/), with contributions from and under the coordination of Ms. Irene Kitsara ([WIPO](http://www.wipo.int/portal/en/index.html)).

##Acknowledgements 

The WIPO Manual on Open Source Tools for Patent Analytics, 2016, was prepared under the direction of Mr. Yo Takagi (Assistant Director General) and under the supervision of Mr. Alejandro Roca Campaña (Senior Director) and Mr. Andrew Czajkowski (Head of Section). Mr. Anthony Cutter prepared and analyzed the survey on the use of tools for patent analytics by patent information professionals. We are grateful to the participants in two regional workshops on patent analytics which took place in 2015 in Rio de Janeiro, Brazil, and Manila, Philippines who were presented with the draft Manual and who provided useful feedback, facilitating the optimization and completion of the Manual. We would also like to thank Ms. Alica Daly, Director of the IP Analytics Hub, IP Australia, as well as Mr. Rich Corken, Head of Informatics at the UK IPO for the fruitful discussions and for sharing their experiences with open source tools. The development of this Manual would have not been possible without the excellent support and troubleshooting provided by the open source tools community.  Ms. Catherine Oldham offered valuable comments throughout the preparation of the report and assistance with editing.  Thanks go to colleagues in the Communications Division and in the Printing Plant for their services. 

##Further information

The electronic version of the report, as well as all datasets mentioned in the Manual and used for the various exercises can be downloaded from the [Manual Github repository](https://github.com/wipo-analytics). 

##Conditions of use

You are welcome to use the information provided in this publication, but please cite WIPO and the Manual as the source. Contact e-mail: patent.information@wipo.int 

##Disclaimer

This Manual does not constitute an exhaustive presentation of all open source tools and the information contained therein was valid at the time of printing.  In addition, the opinions expressed in the Manual do not necessarily reflect the opinion of WIPO Member States.
